### PR TITLE
Added GTM Container file for easy import

### PR DESCRIPTION
**Pull request by DanWilkerson**
Added a GTM container file with the necessary items pre-configured to simply setting things up in Google Tag Manager. Added instructions in the README.md file on how to use the container file. 

Added configurations to both tags to a.) use the default setting for cookies, per normal installation and b.) store the correct page path in the Event as well as the Pageview, a la #340 .

### CODE REVIEW

**Comment by DanWilkerson** [comment]
@luisfarzati This should cut down on issues with configuring GTM. Don't know why I didn't think of it sooner.

**Comment by ProLoser** [comment]
@DanWilkerson I apologize for the hassle, but we are trying to relocate this stuff into their own separate plugins. Would you be at all interested in helping us do the transfer, as I already stubbed out a https://github.com/angulartics/angulartics-google-tag-manager repo. I could add you to that team where you'd be able to relocate the GTM code into that plugin and also add these files to that specific repo.

**Comment by DanWilkerson** [comment]
@ProLoser Happy to!

**Comment by DanWilkerson** [comment]
Closing since the GTM repo has been created/files have been added

**Pull request closed without merging**
