### PR TITLE
Add register user properties to Hubspot plugin

### PR DESCRIPTION
**Pull request by tydanielson**
Hubspot has the ability to track users, adding a identify push call when we set the user properties

### CODE REVIEW

**Comment by ProLoser** [comment]
@tydanielson if I added you to the hubspot team, do you think you'd be willing to help us relocate the hubspot code to https://github.com/angulartics/angulartics-hubspot for us? As you can probably tell we haven't had the time we would like to spend on this project. It would require relocating the src from here to that repo, submitting a PR to this repo to have the old src deleted, but this way you'd be able to integrate your patch.

**Comment by tydanielson** [comment]
Hi Dean,

Ya I'd be happy to as soon as you get me on the team I'll get it submitted.

Thanks,
Tyler

**Comment by tydanielson** [comment]
@ProLoser I'm not sure where to ask this, but I would like to create a plugin for facebook pixel as well... https://developers.facebook.com/docs/facebook-pixel/api-reference I believe I would need someone from the angulartics team to create the repo.

**Comment by timelf123** [comment]
I've added you to the hubspot repo and https://github.com/angulartics/angulartics-facebook-pixel

Thanks!

**Pull request merged**
