### PR TITLE
removed invalid char at the begging of the package.json

### LINKED ISSUE #522: Yarn installation install an invalid package.json
# Description
When I install angulartycs using the new yarn package manager. The package.json is not transformed like npm do.

And there is an invalid char ``ï»¿{`` in the package.json:1:1.

You can test this using a ``head package.json`` and you can see the strange char at the begging.

## Versions
Angulartics: **1.2.1**
OS: **Windows 10**

### PR DESCRIPTION
**Pull request by navarroaxel**
fix #522

### CODE REVIEW

**Comment by timelf123** [comment]
cheers. how did you remove it? I was made aware of this several weeks ago and forgot to look into it further

**Comment by navarroaxel** [comment]
The WebStorm didn't help me, then:
1) copy all the file except the first line.
2) run: echo > package.json
3) paste clipboard
4) add a { in the first line

Thanks for the merge. Can you do a path release with this fix? I want to use yarn.

**Comment by timelf123** [comment]
tagged and pushed as 1.3.0

**Comment by navarroaxel** [comment]
But npm/yarn is still in version 1.2.1

**Comment by timelf123** [comment]
fixed, sorry

**Pull request merged**
