### PR TITLE
Stop $location being started if code not used

### LINKED ISSUE #569: Including this module breaks in-page anchor links without using any of its code
If I have a page that has an Angular module that depends on `angulartics`, the `run` block will invoke `$location` and so change the way in-page anchor links work:
```html
<a href="#top">Go to top</a>
```

Instead of the page url getting `#top` appended, it gets `#/top`, which doesn't scroll the page as it should. This is with Angular 1.4.14. On a regular page that uses Angular+Angulartics in a component manner, I don't think in-page anchors should be stopped.

I have essentially the same problem as #29. The only difference is I'm loading the `angulartics` module (unfortunately that's unavoidable at the moment) even though I'm not using any of it (there's nothing in the page that triggers any of the code that requires `$location`).

### PR DESCRIPTION
**Pull request by henrahmagix**
Move all invocations of `$location` to only where it's used, otherwise
simply including this module will make Angular take control of the
hashbang url, which stops in-page anchors being used.

This is essentially the same as #219 but even more inline, wrapping only the code that uses `$location`.

Fix #569 

Is viewed better [with ?w=1](https://github.com/angulartics/angulartics/pull/570/files?w=1)

### CODE REVIEW

**Comment by henrahmagix** [comment]
Thanks!

**Comment by timelf123** [comment]
np thank you! will cut a release when I am able to - should be within the next day or two

**Comment by timelf123** [comment]
1.6.0 out

**Comment by henrahmagix** [comment]
:tada:

**Pull request merged**
