### PR TITLE
chore(config): update package.json config

### PR DESCRIPTION
**Pull request by icfantv**
* update `package.json` with correct `main` config for es6 support.

### CODE REVIEW

**Comment by icfantv** [comment]
I missed this update with my #436 PR.  Without it, `import angulartics from 'angulartics'` still won't work.

**Comment by timelf123** [comment]
I'll cut a release ASAP, thanks for the fix!

**Comment by icfantv** [comment]
you rock.  thanks.  i apologize for not checking this sooner.  i forgot about updating my project so I didn't catch it until now.

**Comment by timelf123** [comment]
No problem! https://github.com/angulartics/angulartics/releases/tag/1.0.3

**Pull request merged**
