### PR TITLE
Remove page tracking from MIxpanel.

### PR DESCRIPTION
**Pull request by lunks**
Mixpanel advises only tracking some page views events instead of all of them. 
https://mixpanel.com/help/questions/articles/why-measure-events-vs-page-views

### CODE REVIEW

**Comment by lunks** [comment]
We might need a version bump for this. Thoughts?

**Comment by timelf123** [comment]
I think this is ok to merge. I'm planning a big release in the coming weeks that will include a version bump

**Comment by lunks** [comment]
Alright! I released a new version and forgot to merge my own PR. :sweat_smile: 

I'll rebase this.

**Comment by lunks** [comment]
I'll create another PR on the right repo later.

**Pull request closed without merging**
