### PR TITLE
Global opt out feature

### PR DESCRIPTION
**Pull request by NorthMcCormick**
Working on a globally used software we required that it should have an opt out feature for privacy, and we didn't want it to reply specifically on Piwik or your choice of analytics.

This source is honestly fairly cryptic haha, but I did the best I could go bring in the feature with as little overhead as possible, and it shouldn't break anything. The feature also needed to be set on demand in any controller or service so the functions are directly linked with the api variable. 

Obviously any recommendations or help are appreciated.

### CODE REVIEW

**Comment by katak** [comment]
+1

**Comment by DanielCaspers** [comment]
+1! Being able to set this on demand from any controller or service would certainly be beneficial, especially given that users want the option to opt out.

**Comment by NorthMcCormick** [comment]
@DanielCaspers If you pull this in place of the master branch, you still inject $analytics and just use

$analytics.setOptOut(boolean);
`true` for no tracking
`false` for tracking and then you can just have it either save a cookie for offline usage, or when the user logs in just set it via a setting with their profile.

**Comment by timelf123** [comment]
This is great! Would you mind rebasing this down to one commit @NorthMcCormick?

**Comment by daudelin** [comment]
+1 This would be super useful for my team's needs.

**Comment by timelf123** [comment]
thanks @NorthMcCormick for the feature and @daudelin for the reminder

**Pull request merged**
